### ISSUE TITLE
Error executing action `create` on resource 'lvm_volume_group[name]'

### ISSUE THREAD

**Issue by narendramannam** [chef-cookbooks/lvm#107]
### Cookbook version
3.1.0

### Chef-client version
Chef: 12.15.19

### Platform Details
RedHat AMI on AWS - ami-6f68cf0f

### Steps to Reproduce:
take an AMI from AWS cloud which I mentioned above and just run the cookbook with required parameters as per README.md file 

### Expected Result:
expecting volume group to get created

### Actual Result:
Unable to load lvm attributes [lvs.yaml] for version [2.02.166(2)]. The version/object may not be supported or you may need to upgrade the di-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes/2.02.166(2)/lvs.yaml

**Comment by otakumike** [comment]
I think this is a duplicate of #105. FYI I've published a comment in there with a possible temporary fix.

**Comment by tas50** [comment]
This should be fixed in the 4.X series
