### ISSUE TITLE
Make it possible to skip resizefs

### ISSUE THREAD

**Issue by EugenMayer** [chef-cookbooks/lvm#111]
Eventhough i understand why --resizefs is convinient, it uses fsadm which does not support btrfs. This will most probably also never happen, since btrfs needs to be mounted during resize.

This said, it would be great to be able to skip https://github.com/chef-cookbooks/lvm/blob/master/libraries/provider_lvm_logical_volume.rb#L250 --resizefs to handle the resize manually.

Thank you!

**Comment by irvingpop** [comment]
Closed via #160
