### ISSUE TITLE
lvcreate hangs due to lvm lock. 

### ISSUE THREAD

**Issue by rezblaze** [chef-cookbooks/lvm#122]
### Cookbook version
4.0.4

### Chef-client version
12.17.44

### Platform Details
RHEL 7.2

### Scenario:
Create VG and associate LVs

### Steps to Reproduce:
basic cookbook and it fails every time.

### Expected Result:
create VG and associated LV, mounts etc. 

### Actual Result:
# chef-client -r dcos
Starting Chef Client, version 12.17.44
resolving cookbooks for run list: ["dcos"]
Synchronizing Cookbooks:
  - lvm (4.0.4)
  - dcos (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 7 resources
Recipe: dcos::default
  * lvm_logical_volume[lv_docker] action nothing (skipped due to action :nothing)
  * lvm_logical_volume[lv_docker_repos] action nothing (skipped due to action :nothing)
  * lvm_logical_volume[lv_docker_volumes] action nothing (skipped due to action :nothing)
  * lvm_logical_volume[lv_mesosphere] action nothing (skipped due to action :nothing)
  * lvm_logical_volume[lv_mesos] action nothing (skipped due to action :nothing)
  * lvm_logical_volume[lv_dcos] action nothing (skipped due to action :nothing)
  * lvm_volume_group[vg_docker] action create
    * chef_gem[vg_docker_di-ruby-lvm-attrib_removal] action remove (up to date)
    * chef_gem[vg_docker_di-ruby-lvm_removal] action remove (up to date)
    * lvm_logical_volume[lv_docker] action create
      * chef_gem[lv_docker_di-ruby-lvm-attrib_removal] action remove (up to date)
      * chef_gem[lv_docker_di-ruby-lvm_removal] action remove (up to date)

*** Hangs here ***

Cookbook ...

\# cat default.rb 
\#
\# Cookbook Name:: dcos
\# Recipe:: default
\#
\# Copyright (c) 2017 The Authors, All Rights Reserved.
 
lvm_volume_group 'vg_docker' do
  physical_volumes ['/dev/sda']
  wipe_signatures true

  logical_volume 'lv_docker' do
    action :create
    size        '9G'
    filesystem  'xfs'
  end

  logical_volume 'lv_docker_repos' do
    action :create
    size        '15M'
    filesystem  'xfs'
  end

  logical_volume 'lv_docker_volumes' do
    action :create
    size        '4G'
    filesystem  'xfs'
  end

  logical_volume 'lv_mesosphere' do
    action :create
    size        '9G'
    filesystem  'xfs'
  end

  logical_volume 'lv_mesos' do
    action :create
    size        '40G'
    filesystem  'xfs'
  end

  logical_volume 'lv_dcos' do
    action :create
    size        '4G'
    filesystem  'xfs'
  end

end

**Comment by rezblaze** [comment]
trace:

# cat /var/chef/cache/chef-stacktrace.out
Generated at 2017-01-05 07:46:46 -0600
SystemExit: lvm_volume_group[vg_docker] (dcos::default line 7) had an error: SystemExit: lvm_logical_volume[lv_docker_repos] (dcos::default line 110) had an error: SystemExit: exit
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:367:in `exit'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:367:in `fatal!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:64:in `block in setup_signal_handlers'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm/external.rb:12:in `gets'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm/external.rb:12:in `block in cmd'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/open4-0.9.6/lib/open4.rb:68:in `popen4'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm/external.rb:11:in `cmd'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm.rb:49:in `raw'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:64:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:143:in `block in create_logical_volumes'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:141:in `each'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:141:in `create_logical_volumes'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:63:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'

\>>>> Caused by SystemExit: exit
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:367:in `exit'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:367:in `fatal!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:64:in `block in setup_signal_handlers'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm/external.rb:12:in `gets'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm/external.rb:12:in `block in cmd'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/open4-0.9.6/lib/open4.rb:68:in `popen4'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm/external.rb:11:in `cmd'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-ruby-lvm-0.2.2/lib/lvm.rb:49:in `raw'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:64:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:143:in `block in create_logical_volumes'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:141:in `each'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:141:in `create_logical_volumes'
/var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:63:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/chef-client:26:in `<top (required)>'

**Comment by cheeseplus** [comment]
Could you try this with the latest version of the cookbook? It appears we addressed some gem cleanup issues that might help here.

**Comment by iennae** [comment]
If you're still having this problem, please reopen. Thanks!

**Comment by mcapra** [comment]
I ran into a similar issue on the 5.2.2 version, and came to this issue after plenty of Googling. Chucking this on the pile -- no action needed by the maintainers from my perspective.

In my case, because I was in some scenarios creating xfs volumes on top of segments previously used by different xfs volumes, calls to the lvm binary were prompting for user input due to existing xfs volume signatures. That lead me to this RedHat article:
https://access.redhat.com/solutions/5721361

Adding these lv_params was enough to solve my particular problem:
```ruby
lv_params '--wipesignatures y --yes --zero y'
```

This of course comes with some risk, but since all of the volumes my infra cares about are managed in serial as part of the Chef client run, I consider the risk minimal. YMMV.
