### ISSUE TITLE
Need ability to remove 

### ISSUE THREAD

**Issue by sanguis** [chef-cookbooks/lvm#124]
### Cookbook version
4.0.5
### Chef-client version
12.17.44
### Platform Details
Redhat 7 aws ami

### Scenario:
Run a resource that runs lvremove

I would think that lvm_logical_volume would have a :remove action in addition to :create and :resize

### Steps to Reproduce:

NA

### Expected Result:

Trying to delete a logical volume with this cookbook.

### Actual Result:
NA

**Comment by tas50** [comment]
This is now available in the latest version.
