### ISSUE TITLE
 Could not find a valid gem 'di-ruby-lvm-attrib' (= 0.0.28) in any repository

### ISSUE THREAD

**Issue by zackyaz** [chef-cookbooks/lvm#130]
### Cookbook version
cookbook 'lvm', '~> 4.1.0'

### Chef-client version
Chef: 12.19.36

### Platform Details
  Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.3:GA:server
            Kernel: Linux 3.10.0-514.16.1.el7.x86_64
      Architecture: x86-64

### Scenario:
include_recipe "lvm"
lvm_volume_group name do
    physical_volumes volumes
    physical_extent_size '32M'
    logical_volume "data" do
        size "100%VG"
        filesystem 'ext3'
        mount_point :location => location, :options => 'noatime,nodiratime'
        stripes volumes.count
        stripe_size 4
    end
end

### Steps to Reproduce:
include_recipe "lvm"
lvm_volume_group name do
    physical_volumes volumes
    physical_extent_size '32M'
    logical_volume "data" do
        size "100%VG"
        filesystem 'ext3'
        mount_point :location => location, :options => 'noatime,nodiratime'
        stripes volumes.count
        stripe_size 4
    end
end

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[2017-05-03T08:58:55+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-05-03T08:58:55+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-03T08:58:55+00:00] ERROR: lvm_volume_group[vg01r1] (my-jenkins::lvm_config line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: chef_gem[di-ruby-lvm-attrib] (/var/chef/cache/cookbooks/lvm/libraries/lvm.rb line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /opt/chef/embedded/bin/gem install di-ruby-lvm-attrib -q --no-rdoc --no-ri -v "0.0.28" ----
STDOUT:
STDERR: ERROR:  Could not find a valid gem 'di-ruby-lvm-attrib' (= 0.0.28) in any repository
ERROR:  Possible alternatives: di-ruby-lvm-attrib
---- End output of /opt/chef/embedded/bin/gem install di-ruby-lvm-attrib -q --no-rdoc --no-ri -v "0.0.28" ----
Ran /opt/chef/embedded/bin/gem install di-ruby-lvm-attrib -q --no-rdoc --no-ri -v "0.0.28" returned 2
[2017-05-03T08:58:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by zackyaz** [comment]
Hi

the lvm is
lvm> version
  LVM version:     2.02.166(2)-RHEL7 (2016-11-16)
  Library version: 1.02.135-RHEL7 (2016-11-16)
  Driver version:  4.34.0

2.02.166(2) is not exist in 0.0.27

di-ruby-lvm-attrib version 0.0.28 is in the default attribute in the lvm cookbook

thank and regards Zacky

**Comment by iennae** [comment]
As per the README:

> 
This cookbook has used multiple variants of the ruby-lvm and ruby-lvm-attrib gems for interacting with LVM. Most recently we used di-ruby-lvm and di-ruby-lvm-attrib gems, which are no longer being maintained. As of the 4.0 release this cookbook uses new Chef maintained gems: chef-ruby-lvm and chef-ruby-lvm-attrib. The cookbook will first remove the old gems before load/installing the new gems, in order to prevent gem conflicts. If you previously used attributes to control the version of the gems to install, you will need to update to the latest attribute names to maintain that functionality.

You need to update the attributes to not use di-ruby-lvm-attrib:

> default['lvm']['chef-ruby-lvm']['version'] = '0.2.2'
> default['lvm']['chef-ruby-lvm-attrib']['version'] = '0.0.28'

**Comment by iennae** [comment]
Please reopen if you are still having issues after updating the attributes.
