### ISSUE TITLE
Defining multiple logical volumes triggers resource cloning deprecation

### ISSUE THREAD

**Issue by trickyearlobe** [chef-cookbooks/lvm#152]
### Cookbook version
4.1.13

### Chef-client version
Customer is using 12.18.31 and has enabled `deprecations as errors` to catch problems before they migrate to Chef Client 14.x

### Platform Details
Suse Linux (version unknown)

### Scenario:
A cookbook containing two `lvm_logical_volume` resources with different names fails with a resource cloning deprecation.

### Cause:
On SUSE Linux, the method `action_create` in `Chef::Provider::LvmLogicalVolume` calls `install_filesystem_deps` which in turn calls `package 'e2fsprogs'`.

When we have multiple LV's defined, `action_create` gets called multiple times resulting in `package "e2fsprogs"` being called multiple times.

To avoid resource cloning we need to call `package "e2fsprogs"` once.

**Comment by tas50** [comment]
Resolved in 4.1.14
