### ISSUE TITLE
Red Hat 8.2: Unable to load lvm attributes [lvs.yaml] for version [2.03.09(2)]

### ISSUE THREAD

**Issue by Chiango2** [chef-cookbooks/lvm#198]
Chef-client version
15.7.32

Platform Details
Red Hat Enterprise Linux 8.3

System Info:
           ------------
chef_version=15.7.32
platform=redhat        
platform_version=8.3
ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
program_name=/opt/chef/bin/chef-client
executable=/opt/chef/bin/chef-client

Scenario:
LVM is complaining about missing lvm attributes version 02.03.09(2). chef-ruby-lvm-attrib-0.2.3

Error:
 Unable to load lvm attributes [lvs.yaml] for version [2.03.09(2)]. The version/object may not be supported or you may need to upgrade the chef-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-ruby-lvm-attrib-0.2.3/lib/lvm/attributes/2.03.09(2)/lvs.yaml]

**Comment by gaelik** [comment]
Submitted a PR for that one for the gem
https://github.com/chef/chef-ruby-lvm-attrib/pull/31

**Comment by tas50** [comment]
0.3.6 of the gem is uploaded now

**Comment by Chiango2** [comment]
Seems chef-ruby-lvm-attrib gem version 0.3.6 - November 13, 2020 (49.5 KB) fixed the issue
