### ISSUE TITLE
"resizes the PV to fill the remaining space" bats test fails on CentOS 5

### ISSUE THREAD

**Issue by juliandunn** [chef-cookbooks/lvm#48]
This integration test fails on CentOS 5 but is fine on CentOS 6.

**Comment by juliandunn** [comment]
@spion06 if you have time perhaps you could look at this since you wrote the test originally?

**Comment by spion06** [comment]
I actually got poked about this recently and totally forgot about this issue getting logged.

When investigating I found that the version of losetup that centos 5 has doesn't support loop device resizing (the -c option). From what I have been able to see centos 5 is the only platform with that old of a version of losetup. 

I don't think that's something i'll be able to fix unless i can look into compiling a newer version of losetup for centos 5 which isn't something I would prefer to do.

**Comment by tas50** [comment]
We're all green now
