### ISSUE TITLE
Check if a mount is allready mounted

### ISSUE THREAD

**Issue by gimler** [chef-cookbooks/lvm#50]
`libraries/provider_lvm_logical_volume.rb` the mount resource should use the `mounted` attribute to only execute the mount if it ist not allready mounted.

**Comment by MarkGibbons** [comment]
Hello @gimler,  I don't think the mount resource remounts files that are already mounted.  Looking at the chef-client mount code it doesn't look as if, as far as I can tell, that the mounted attribute of the mount resource is used to change the provider's behavior at all.  What do you want to cause to happen by specifying the mounted attribute?

Regards,
  Mark

**Comment by tas50** [comment]
This should be handled with the idempotency of the chef mount provider. It will only remount if something has changed.
