### ISSUE TITLE
Version bump requested

### ISSUE THREAD

**Issue by Seth-Karlo** [chef-cookbooks/lvm#69]
Hi there!

I'm using the lvm cookbook for my gluster cookbook, but the current frozen version of the cookbook in the supermarket is missing the latest lvm drivers. These are in master though, could a new version be released please?

Thanks in advance!

Andy

**Comment by tas50** [comment]
I'm working my way alphabetically down the list.  LVM will be soon.

**Comment by Seth-Karlo** [comment]
If you'd like someone to help sort out operational loads I'm happy to help.

**Comment by tas50** [comment]
Going out n ow
