### ISSUE TITLE
support for -T (thin pool) option

### ISSUE THREAD

**Issue by habelson** [chef-cookbooks/lvm#70]
Is there support for lvm -T option. I am unable to find info:

from man lvcreate:

-T, --thin, --thinpool ThinPoolLogicalVolume{Name|Path} Creates thin pool or thin logical volume or both. Specifying the optional argument --size will cause the creation of the thin pool logical volume. Specifying the optional argument --virtualsize will cause the creation of the thin logical volume from given thin pool volume. Specifying both arguments will cause the creation of both thin pool and thin volume using this pool. Requires device mapper kernel driver for thin provisioning from kernel 3.2 or newer.

**Comment by habelson** [comment]
I see now there is the undocumented lv_params attribute, unfortunately, there is an issue where --name is always used, and is not compatible with the -T option

**Comment by tas50** [comment]
Thin pools are now supported
