### ISSUE TITLE
LVM Ruby gem is broken as of today

### ISSUE THREAD

**Issue by dgarstang** [chef-cookbooks/lvm#80]
It looks like the di-ruby-lvm was updated from 0.1.3 to 0.2.2 TODAY. This seems to be causing this cookbook to fail with "undefined method `list' for :LVM::PhysicalVolumes" when using the lvm_volume_group resource, like this:

```
 27:   lvm_volume_group 'vg00' do
 28:     physical_volumes physical_disks
 29:     logical_volume "#{node['slice-bootstrap-node']['instance_store']['name']}" do
 30:       size        "#{node['slice-bootstrap-node']['instance_store']['size']}"
 31:       filesystem  "#{node['slice-bootstrap-node']['instance_store']['fs_type']}"
 32:       mount_point location: "#{node['slice-bootstrap-node']['instance_store']['mount_point']}", options: 'defaults,nofail,nobootwait'
 33:       stripes physical_disks.length
 34:     end
 35:   end
 36:
```

**Comment by odolbeau** [comment]
Same problem here.

**Comment by dgarstang** [comment]
Actually, I think this is a non issue. We were installing the ruby gem earlier, without pinning. I looked at the lvm cookbook and it seems to be installing the older 0.1.3 version, so all we have to do is remove the earlier install and 0.1.3 should be installed. Currently testing.

**Comment by petecheslock** [comment]
Also hit this issue - installing 0.1.3 and pinning to that version works for the latest version of this cookbook

**Comment by tas50** [comment]
@petecheslock How are you installing the gem?  The cookbook is still installing the correct version.

**Comment by petecheslock** [comment]
Bah - you know what i'm totally on an older version of this CB and didn't see you set the version pins in here https://github.com/chef-cookbooks/lvm/blob/master/attributes/default.rb

Should be all good.

**Comment by tas50** [comment]
I'll close this one out and open an issue for figuring out why 0.2.0 breaks it.  We should be running the latest without issues.

**Comment by odolbeau** [comment]
Again, same problem here.
Running an old version of lvm which don't fix the `di-ruby-lvm` version.
