### ISSUE TITLE
di-ruby-lvm 0.2.0 compatibility

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/lvm#81]
We need to ensure we can upgrade to di-ruby-lvm 0.2.0, which currently breaks the cookbook.  See #80 for details

**Comment by ChiefAlexander** [comment]
The gem di-ruby-lvm was updated lately to be able to process multiple file-systems better. A minor refactoring of the code was done and then released. Unfortunately the version of di-ruby-lvm (0.2.0) that was released had a method outside of a class within physical_volumes.rb. A new release was made and pushed to ruby gems (0.2.1) which fixes this issue.

**Comment by eheydrick** [comment]
I think this can be closed now that 1.5.0 is out.
