### ISSUE TITLE
undefined method `list' when using volume group providers if the gem isn't loaded

### ISSUE THREAD

**Issue by davgibney1** [chef-cookbooks/lvm#84]
I've tried debugging this a hundred ways, but I can't get lvm 1.4.1 with Chef 12.4 to work at all.... Error follows:
- lvm_physical_volume[/dev/xvdb1] action create (up to date)
  - lvm_volume_group[/dev/vg1] action create
    # 
    # Error executing action `create` on resource 'lvm_volume_group[/dev/vg1]'
    ## NoMethodError
    
    undefined method `list' for #LVM::PhysicalVolumes:0x000000073cb818
    ## Cookbook Trace:
    
    /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:124:in `create_volume_group'
    /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:58:in`action_create'
    ## Resource Declaration:
    # In /var/chef/cache/cookbooks/carvemystorage/recipes/mongodb_layout.rb
    
    43: lvm_volume_group '/dev/vg1' do
    44:
    45:   physical_volumes ['/dev/xvdb1']
    46:   #only_if { File.exist?('/dev/xvdb1' )}
    47: end
    48:
    ## Compiled Resource:
    # Declared in /var/chef/cache/cookbooks/carvemystorage/recipes/mongodb_layout.rb:43:in `from_file'
    
    lvm_volume_group("/dev/vg1") do
      provider Chef::Provider::LvmVolumeGroup
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :lvm_volume_group
      cookbook_name "carvemystorage"
      recipe_name "mongodb_layout"
      physical_volumes ["/dev/xvdb1"]
    end

Running handlers:
[2015-12-04T13:28:06-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-12-04T13:28:06-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 9.179841209 seconds
[2015-12-04T13:28:07-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-12-04T13:28:07-05:00] ERROR: lvm_volume_group[/dev/vg1](carvemystorage::mongodb_layout line 43) had an error: NoMethodError: undefined method `list' for #LVM::PhysicalVolumes:0x000000073cb818
[2015-12-04T13:28:07-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by ChiefAlexander** [comment]
The gem di-ruby-lvm was updated lately to be able to process multiple file-systems better. A minor refactoring of the code was done and then released. Unfortunately the version of di-ruby-lvm (0.2.0) that was released had a method outside of a class within physical_volumes.rb. A new release was made and pushed to ruby gems (0.2.1) which fixes this issue. Try installing the previous version of this gem (0.1.3) or installing the latest version in which this issue should be resolved.

**Comment by davgibney1** [comment]
Thank you very much for the helpful information. Once I added the following code to my recipe, everything worked,

chef_gem 'di-ruby-lvm' do
version  "0.2.1"
action  :install
end

**Comment by tas50** [comment]
We should be trying to load the gem and failing with a real message if it's not present.  It wouldn't be too crazy to add that.

**Comment by tas50** [comment]
With the auto gem install this is no longer an issue.
