### ISSUE TITLE
Amazon Linux 2015.09

### ISSUE THREAD

**Issue by joshpollara** [chef-cookbooks/lvm#85]
When the 'lvm vgcreate' command is executed on Amazon Linux 2015.09 it waits for the user to confirm the action. This causes a chef run to never complete. I think all of the lvm commands should include "--yes" as to not prompt the user.

**Comment by Ghilteras** [comment]
there is already a PR for this:

https://github.com/chef-cookbooks/lvm/pull/74

**Comment by tas50** [comment]
Fixed with the merging of #74
