### ISSUE TITLE
Recipe for SuSE fails in version 2.1.0

### ISSUE THREAD

**Issue by kostaatsap** [chef-cookbooks/lvm#96]
### Cookbook version

2.1.0
### Chef-client version

Chef: 11.18.12
### Platform Details

Suse 11.3 (SLES11 SP3) 64bit
### Scenario:

Create LVM Volumes/Groups. I have been using this recipe for a few months now without any issues. Everything used to work perfectly until version 2.0.0. For some reason there is an issue in my environment with version 2.1.0
### Steps to Reproduce:

Creating an LVM Group:

``` ruby
  include_recipe "lvm"
  volumes =  Dir.glob("/dev/data*")
  lvm_volume_group "vg01r1" do
    physical_volumes volumes
    physical_extent_size "32M"
    logical_volume "backup" do
      size '100%VG'
      filesystem "xfs"
      mount_point :location => "/backup", :options => "noatime,nodiratime"
      stripes volumes.count
      stripe_size 4
    end
  end
```
### Expected Result:

Recipe should run
### Actual Result:

``` bash
Generated at 2016-05-13 16:10:00 +0000
NoMethodError: undefined method `lvm_logical_volume' for Chef::Resource::LvmVolumeGroup
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:300:in `method_missing'
/var/lib/chef/cookbooks/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'
```

**Comment by tas50** [comment]
@kostaatsap I'm not able to reproduce this on suse 13.2 with Chef 12.17 and the 4.0 cookbook. Can you take a look with a new chef / cookbook and see if this is still an issue.
